import tibetImg from './images/tours/tibetTitleImg.webp';
import javaImg from './images/tours/javaTitleImg.webp';
import hongKongImg from './images/tours/hongKongTitleImg.webp';
import kenyaImg from './images/tours/kenyaTitleImg.webp';
import cambodiaImg from './images/tours/cambodiaTitleImg.webp';
import japanImg from './images/tours/japanTitleImg.webp';

export const pageLinks = [
  {
    id: 1,
    href: '#home',
    text: 'home',
  },
  {
    id: 2,
    href: '#about',
    text: 'about',
  },
  {
    id: 3,
    href: '#services',
    text: 'services',
  },
  {
    id: 4,
    href: '#tours',
    text: 'tours',
  },
];

export const pageIcons = [
  {
    id: 1,
    href: 'https://www.facebook.com',
    iconInfo: 'fab fa-facebook',
  },
  {
    id: 2,
    href: 'https://www.twitter.com',
    iconInfo: 'fab fa-twitter',
  },
  {
    id: 3,
    href: 'https://www.squarespace.com',
    iconInfo: 'fab fa-squarespace',
  },
];

export const serviceDetails = [
  {
    id: 1,
    iconInfo: 'fas fa-socks fa-fw',
    title: 'local lifestyle',
    content:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
  },
  {
    id: 2,
    iconInfo: 'fas fa-tree fa-fw',
    title: 'eco sustainability',
    content:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
  },
  {
    id: 3,
    iconInfo: 'fas fa-wallet fa-fw',
    title: 'cost saving',
    content:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
  },
];

export const tours = [
  {
    id: 1,
    tourImg: tibetImg,
    tourStart: 'august 26th, 2023',
    tourTitle: 'the Tibetan Adventure',
    tourContent:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.',
    tourCountry: 'china',
    tourDays: 6,
    tourStartPrice: 2100,
  },
  {
    id: 2,
    tourImg: javaImg,
    tourStart: 'october 1th, 2023',
    tourTitle: 'the best of java',
    tourContent:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.',
    tourCountry: 'indonesia',
    tourDays: 11,
    tourStartPrice: 1400,
  },
  {
    id: 3,
    tourImg: hongKongImg,
    tourStart: 'september 13th, 2023',
    tourTitle: 'Exploring hong kong',
    tourContent:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.',
    tourCountry: 'hong kong',
    tourDays: 8,
    tourStartPrice: 5000,
  },
  {
    id: 4,
    tourImg: kenyaImg,
    tourStart: 'july 12th, 2023',
    tourTitle: 'the kenyan highlights',
    tourContent:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.',
    tourCountry: 'kenya',
    tourDays: 20,
    tourStartPrice: 3300,
  },
  {
    id: 5,
    tourImg: cambodiaImg,
    tourStart: 'november 7th, 2023',
    tourTitle: 'the cambodian escapade',
    tourContent:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.',
    tourCountry: 'cambodia',
    tourDays: 12,
    tourStartPrice: 1500,
  },
  {
    id: 6,
    tourImg: japanImg,
    tourStart: 'december 5th, 2023',
    tourTitle: 'the japan experience',
    tourContent:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.',
    tourCountry: 'japan',
    tourDays: 21,
    tourStartPrice: 4200,
  },
];

export const test = [];

// 'variety, nature, lifestyle,dreams, wonder, beauty, culture',
export const experiences = [
  '|',
  '|',
  '|',
  'v|',
  'va|',
  'var|',
  'vari|',
  'varie|',
  'variet|',
  'variety|',
  'variety|',
  'variety|',
  'variety|',
  'variety|',
  'variet|',
  'varie|',
  'vari|',
  'var|',
  'va|',
  'va|',
  'v|',
  '|',
  '|',
  '|',
  'n|',
  'na|',
  'nat|',
  'natu|',
  'natur|',
  'nature|',
  'nature|',
  'nature|',
  'nature|',
  'nature|',
  'natur|',
  'natu|',
  'nat|',
  'na|',
  'n|',
  '|',
  '|',
  '|',
  'l|',
  'li|',
  'lif|',
  'life|',
  'lifes|',
  'lifest|',
  'lifesty|',
  'lifestyl|',
  'lifestyle|',
  'lifestyle|',
  'lifestyle|',
  'lifestyle|',
  'lifestyle|',
  'lifestyl|',
  'lifesty|',
  'lifest|',
  'lifes|',
  'life|',
  'lif|',
  'li|',
  'l|',
  '|',
  '|',
  '|',
  'd|',
  'dr|',
  'dre|',
  'drea|',
  'dream|',
  'dreams|',
  'dreams|',
  'dreams|',
  'dreams|',
  'dreams|',
  'dream|',
  'drea|',
  'dre|',
  'dr|',
  'd|',
  '|',
  '|',
  '|',
  'w|',
  'wo|',
  'won|',
  'wond|',
  'wonde|',
  'wonder|',
  'wonder|',
  'wonder|',
  'wonder|',
  'wonder|',
  'wonde|',
  'wond|',
  'won|',
  'wo|',
  'w|',
  '|',
  '|',
  '|',
  'c|',
  'cu|',
  'cul|',
  'cult|',
  'cultu|',
  'cultur|',
  'culture|',
  'culture|',
  'culture|',
  'culture|',
  'culture|',
  'cultur|',
  'cultu|',
  'cult|',
  'cul|',
  'cu|',
  'c|',
  '|',
  '|',
  '|',
  'b|',
  'be|',
  'bea|',
  'beau|',
  'beaut|',
  'beauty|',
  'beauty|',
  'beauty|',
  'beauty|',
  'beauty|',
  'beaut|',
  'beau|',
  'bea|',
  'be|',
  'b|',
];
